export const products = [
  {id:1 ,
    name: 'Pharmacy Boxes',
    image: '../images/1-pharmacy-boxes.webp',
    description: 'Premium quality packaging for pharmaceutical products.',
    price: '12.99',
  },
   {id:2,
    name: 'Azithromycin',
    image: '../images/alamy.jpg',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
   {id:3,
    name: 'Azithromycin',
    image: '../images/azet.webp',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
    {id:4,
    name: 'Azithromycin',
    image: '../images/calvam.webp',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
    {id:5,
    name: 'Azithromycin',
    image: '../images/candi.webp',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
   {id:6,
    name: 'Azithromycin',
    image: '../images/confem.png',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
  {id:7,
    name: 'Azithromycin',
    image: '../images/glimestar.jpg',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
    {id:8,
    name: 'Azithromycin',
    image: '../images/ibuprofen.webp',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
    {id:9,
    name: 'Azithromycin',
    image: '../images/merohit.jpeg',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
    {id:10,
    name: 'Azithromycin',
    image: '../images/omeprazol.jpg',
    description: 'Broad-spectrum antibiotic effective against various bacterial infections.',
    price: '24.99',
  },
 
];
